############################################################################################
# Coursera Course: Exploratory Data Analysis, Winter 2016
# Course Project 1, Part 4: Generate a figure containing 4 panels
#
#     plot4.R loads a UCI data set that contains information about power consumption of one
#     household and generates a figure that contains the following plots for data between
#     January 1 and 2 of 2007:
#           Global Active Power vs. Time
#           Voltage vs. Time
#           Energy Sub Metering vs. Time
#           Global Reactive Power vs. Time
#
#     The values under "sub_metering_2" were divided by 5, the values under
#     "global_active_power" were divided by 500, voltage was divided by 112, and the sub
#     metering values were zeroed in order to match the range of the y-axis of the figure
#     created by the instructor.
#
#     Libraries required: chron
#
#     github/sylvest00, 2015
###########################################################################################


# Clear workspace and close all figures
rm(list = ls())
graphics.off()


# Load calendar library
library(chron)


# Load power consumption data from TXT file
dataTableOriginal <- read.table("household_power_consumption.txt", sep=";",header=TRUE)
dT <- dataTableOriginal


# Convert date objects to characters
dT$Date <- strptime(dT$Date,format="%d/%m/%Y")


# Subset the table to keep data from target dates
day1_idx <- which(dT$Date == "2007-02-01")
day2_idx <- which(dT$Date == "2007-02-02")
idx <- cbind(day1_idx, day2_idx)
idx <- sort(idx)
dT <- dT[idx,]


# Generate x values so that the data is ordered properly and the
# x-axis labels are easily manipulable. Here, they are converted
# to minutes ranging from 1 to 2879
day1_idx <- which(dT$Date == "2007-02-01")
day2_idx <- which(dT$Date == "2007-02-02")
minPerDay <- 60*24;
x <- minPerDay*as.numeric(times(dT$Time))
x[day2_idx] <- x[day2_idx] + minPerDay 
datesList <- unique(dT$Date)
dayLabel <- c(weekdays(as.Date(c(datesList,as.Date(datesList[2])+2),'%Y-%m-%d')))


# Generate data frames for each plot
# Global Active Power plot data frame
dT1 <- data.frame(dT[,c(2,3)])
dT1$Global_active_power <- as.numeric(dT$Global_active_power)/500


# Voltage plot data frame
dT2 <- data.frame(dT[,c(1,5)])
dT2$Voltage <- as.numeric(dT$Voltage)


# Sub metering plot data frame
dT3 <- data.frame(dT[,c(1,2,7,8,9)])
dT3$Sub_metering_1 <- as.numeric(dT3$Sub_metering_1)
dT3$Sub_metering_2 <- as.numeric(dT3$Sub_metering_2)
dT3$Sub_metering_3 <- as.numeric(dT3$Sub_metering_3)


# Global reactive power plot data frame
dT4 <- data.frame(dT[,c(1,4)])
dT4$Global_reactive_power <- as.numeric(dT4$Global_reactive_power)







#### Generate Plots in Figure ####

# Open PNG graphics device
png("plot4.png",width=480,height=480,bg="transparent")

# Initialize query for graphical objects
par(mfrow = c(2,2))

# Plot 1: Global Active Power vs. Time
plot(x,dT1$Global_active_power,
     type="l",
     main = "Global Active Power",
     xlab = "Day",
     xaxt = "n",
     ylab = "Global Acive Power (Kilowatts)"
)

# Add labels for x-axis
axis(1, at = c(1,minPerDay+1,length(x)), labels = dayLabel)




# Plot 2: Voltage vs. Time
# Adjust Voltage values so that the figure is within the same range
# as the figure generated by the instructors
plot(x,227+dT2$Voltage/112,
     main = "Voltage",
     xlab = "Day",
     xaxt = "n",
     type = "l",
     ylab = "Voltage"
)

# Add labels for x-axis
axis(1, at = c(1,minPerDay+1,length(x)), labels = dayLabel)




# Plot 3: Energy Sub Metering vs. Time
# Zero the sub metering values
lineRange1 <- matrix(range(dT3$Sub_metering_1), ncol = 2)
lineRange2 <- matrix(range(dT3$Sub_metering_2), ncol = 2)
lineRange3 <- matrix(range(dT3$Sub_metering_3), ncol = 2)
lineRange0 <- rbind(lineRange1,lineRange2,lineRange3)
lineRange <- c(min(lineRange0),max(lineRange0))
idx <- which(lineRange0[,1] != 0)
for(i in 1:3)
{
  if(i %in% idx)
  {
    dT3[,i+2] <- dT3[,i+2] - lineRange0[i,1]
  }
}

# Find the range for the y-axis
lineRange <- c(range(dT3$Sub_metering_1),range(dT3$Sub_metering_2),range(dT3$Sub_metering_3))
lineRange <- c(min(lineRange),max(lineRange))

# Plot sub metering 1
plot(x,dT3$Sub_metering_1,
     type="l",
     xlab = "Day",
     ylim = c(0,lineRange[2]),
     xaxt = "n",
     ylab = "Energy Sub Metering",
     col = "black"
)

# Plot submetering 2
lines(x,dT3$Sub_metering_2/5, col = "red")

# Plot submetering 3
lines(x,dT3$Sub_metering_3, col = "blue")

# Add labels for x-axis
axis(1, at = c(1,minPerDay+1,length(x)), labels = dayLabel)
title("Energy Sub Metering")

# Add legend
headerNames <- colnames(dT3)[3:5]
legend(x = "topright",headerNames,col = c("black","red","blue"),lwd = c(2.5,2.5,2.5),bty="n")




# Plot 4: Global Reactive Power vs. Time
plot(x,dT4$Global_reactive_power,
     main = "Global Reactive Power",
     xlab = "Day",
     xaxt = "n",
     type = "l",
     ylab = "Global Reactive Power"
)

# Add labels for x-axis
axis(1, at = c(1,minPerDay+1,length(x)), labels = dayLabel)


# Close graphics device
dev.off()